### ISSUE TITLE
search() not working as expected

### ISSUE THREAD

**Issue by greg-maceachern12** [mwpenny/kijiji-scraper#14]
When I call search() using the parameters you provided, I get a error saying "Kijiji failed to redirect to search results". Looking at the code, it only returns that message when its not a redirect (statuscode != 301).
![screen shot 2018-10-29 at 12 14 58 pm](https://user-images.githubusercontent.com/26700336/47663984-7dea5a80-db74-11e8-9124-4913d750c7de.png)

However, looking at the response, the status code received was a 200.
![screen shot 2018-10-29 at 12 11 32 pm](https://user-images.githubusercontent.com/26700336/47664002-82167800-db74-11e8-9ea0-2a56dec305a3.png)

My code:
![image](https://user-images.githubusercontent.com/26700336/47673874-3a9be600-db8c-11e8-8553-81ae7b6b5fa3.png)

**Comment by mwpenny** [comment]
Thank you for the detailed information. I am looking into this now. It's possible that something changed on the Kijiji site.

**Comment by mwpenny** [comment]
Hm, I'm unable to reproduce the problem using the code you provided - everything works as expected. Are you able to do it reliably? If yes, please attach a HAR file of the browser traffic during reproduction (for example, see https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting).

**Comment by greg-maceachern12** [comment]
[localhost.har.zip](https://github.com/mwpenny/kijiji-scraper/files/2527836/localhost.har.zip)

**Comment by greg-maceachern12** [comment]
I'm thinking it could be linked to the fact that I'm using localhost to test, although, even when I use ngrok, I still get the same error

**Comment by mwpenny** [comment]
Ah, got it. You're experiencing this problem because you're running everything in a web browser where it is not possible to suppress the following of redirects. Consequently, `getPageResults()` can't intercept the URL Kijiji redirects the client to in order to modify it for pagination.

Notice in your screenshot that the HTTP response's `_fetchResponse` property has a boolean property called `redirected` which is set to `true` despite the fact that the `followRedirect` option is passed to the `request` module as `false`.

**Comment by mwpenny** [comment]
This limitation should be possible to work around. I'll take a look at what's required (you can as well :smile:). In the mean time, you'd have to run the scraper server-side.

**Comment by greg-maceachern12** [comment]
hmm interesting. Thanks for the info!

**Comment by greg-maceachern12** [comment]
I edited the function a bit which hacks its way around the problem. Not the best approach but works haha!
`
 function getPageResults(params, pageNum) {

    return new Promise(function(resolve, reject) {

        request({"url": KIJIJI_SEARCH_URL, "qs": params, followRedirect: true}, function(err, res) {
            if (err)
                return reject(err);
            let location = res.url.split('www.kijiji.ca')[1];

            request(KIJIJI_BASE_URL + location, function(err, res) {
                if (err)
                    return reject(err);

                let results = parseResultsHTML(res.body);
                if (!results)
                    return reject(new Error("Invalid Kijiji HTML on search results page"));
                resolve(results);
            });
        });
    });}
`

**Comment by mwpenny** [comment]
Glad you got it working for your project. I've just pushed a branch called `redirect-fix`. Could you try it out? It tries to interrupt the redirect by default but has a fallback for situations like yours.

I've also optimized it a bit so that the initial search + redirect only happens for the first page of results. This should noticeably reduce search times when retrieving many pages of results while automatically following redirects (i.e., your use case). Otherwise (as with your hack), ~double the amount of data will be downloaded.

**Comment by greg-maceachern12** [comment]
still getting an error. Saying it can't find the url
![image](https://user-images.githubusercontent.com/26700336/47825756-0ec65f00-dd4a-11e8-83d4-c5a66e6f39c3.png)

**Comment by mwpenny** [comment]
Are you using the same code as before? Could you add a `console.log(res)` in `initFirstResultPagePath()` (https://github.com/mwpenny/kijiji-scraper/blob/redirect-fix/lib/search.js#L105)

**Comment by mwpenny** [comment]
I'd also like to see what `pageLocation` is when execution reaches this line https://github.com/mwpenny/kijiji-scraper/blob/redirect-fix/lib/search.js#L126

**Comment by greg-maceachern12** [comment]
I pulled the branch and replaced my hack with your code. This is what `res` is logging
![image](https://user-images.githubusercontent.com/26700336/47826162-7aa9c700-dd4c-11e8-86fe-1a77c193ccd3.png)

This is what `pageLocation` is logging
![image](https://user-images.githubusercontent.com/26700336/47826170-85fcf280-dd4c-11e8-8a66-1729d64afda4.png)

**Comment by mwpenny** [comment]
Strange. `request` is behaving as if the redirect was suppressed, but the response is not. What's in `res.request`? You have it collapsed in your screenshot. Could you attach `res` as JSON?

**Comment by greg-maceachern12** [comment]
[body.json.zip](https://github.com/mwpenny/kijiji-scraper/files/2536817/body.json.zip)

**Comment by greg-maceachern12** [comment]
It seems to be fetching the correct data. It's just returning it at all.

**Comment by mwpenny** [comment]
Oh, I meant the entire `res` object. Not just `res.body`.

It would appear that way, yes. What I need to parse out is the URL of the page that it redirects to, but it looks like the response object has a different structure for you than it does when running on nodejs.

**Comment by greg-maceachern12** [comment]
[document.json.zip](https://github.com/mwpenny/kijiji-scraper/files/2536877/document.json.zip)

**Comment by mwpenny** [comment]
Perfect, thanks. It seems that in your environment, the response object contains information about the _original_ request URL and not the one that was redirected to (likely because `followRedirect` is passed as `false`). I've updated the `redirect-fix` branch (hopefully for the last time; the redirect is explicitly followed now - a little bit more to download for the first page, but a probable fix). Give it a try

**Comment by greg-maceachern12** [comment]
Getting the same error.
![image](https://user-images.githubusercontent.com/26700336/47851225-5da5e000-ddae-11e8-8981-4625b29d5934.png)
[document (1).json.zip](https://github.com/mwpenny/kijiji-scraper/files/2538471/document.1.json.zip)

**Comment by mwpenny** [comment]
I'm going to refactor the code to use [node-fetch](https://www.npmjs.com/package/node-fetch) instead of request so that the API is the same in both the browser and node.

**Comment by greg-maceachern12** [comment]
Sounds good! Thanks a lot :)

**Comment by mwpenny** [comment]
Alright, we should be good to go! Pull `redirect-fix` and try again. If it doesn't work, I'd like to see the `res` object (specifically `res.url`) returned by the `fetch()` call in `initFirstResultPagePath()`.

**Comment by greg-maceachern12** [comment]
Works perfect! Just did a bunch of testing. Thanks a ton

**Comment by mwpenny** [comment]
Awesome! I'll merge+push to NPM later today. Good luck with your project :)
